# Site
name: "Drishti"
title: "Drishti"
description: ""  
logo: 'assets/images/logo-dark.png'
logo-full: 'assets/images/logo-dark-full.png'
favicon: 'assets/images/logo-dark.png'
baseurl: ''
google_analytics: 'G-577MRTS9CK'
disqus: 'drishti-iitdh'
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: drishti@iitdh.ac.in
instagram: drishti.iitdh
linkedin: drishti-iit-dharwad

# Team
team:
  subham:
    display_name: Subham Kumar
    short_name: Subham
    sub_role: Overall Coordinator, Journalist
    avatar: subham.jpg
    email: 200020047@iitdh.ac.in
    bio: Passionate journalist, avid traveler, and social advocate. Through my words, I uncover untold stories, highlight social issues, and inspire change. Join me on a journey to uncover untold stories, highlight social issues, and inspire change as we make a positive impact, one story at a time.
    instagram: kanwat_shubham
    twitter: shub6535
  om:
    display_name: Om Patil
    short_name: Om
    sub_role: Editor
    avatar: om.jpg
    email: 200010036@iitdh.ac.in
    web: https://modernoctave.github.io/
    instagram: om.s.patil
    linkedin: om-patil-032915204
    bio: Programmer, Roboticist, Linux Enthusiast, and an Aspiring ML Researcher but above all a journalist at heart!
  shahil:
    display_name: Shahil Patel
    short_name: Shahil
    sub_role: Designer
    avatar: shahil.jpg
    email: 200010039@iitdh.ac.in
    linkedin: shahil-patel-97298b1bb
    bio: A programming and graphic design enthusiast and experienced team leader, creating innovative solutions, leading graphic design projects, and crafting visually stunning designs.
  atharva:
    display_name: Atharva Virendra Tijare
    short_name: Atharva
    avatar: atharva.jpg
    email: atharvatijare04@gmail.com
    instagram: atharva.tijare
    linkedin: atharva-virendra-tijare-b0a926258
    bio: A passionate coder, exploring the endless possibilities of technology. With a unique blend of technical expertise and critical sense of art and design. Embracing innovation with elegance!
  sid:
    display_name: Siddhartha Prasad
    short_name: Sid
    avatar: siddhartha.jpg
    email: 210030033@iitdh.ac.in
    instagram: siddhartha_pd
    bio: From the passionate city of Patna, believes in humanity, science buff, loves to design and edit, and Gamer by birth.
  mahesh:
    display_name: Mahesh Krishnam
    short_name: Mahesh
    avatar: mahesh.webp
    email: 220120011@iitdh.ac.in
    instagram: krishnam_mahesh
    linkedin: mahesh-krishnam-a8a0b422b
    twitter: Krishnam_Mahesh
    bio: From Patna, Bihar. Exploring the infinite possibilities.
  yash:
    display_name: Yash Satish Kute 
    short_name: Yash
    avatar: yash.jpg
    email: yashkute762@gmail.com
    instagram: yash2805k
    linkedin: yash-kute-3714aa253
    bio: "Delivering captivating campus stories with wit and a unique perspective. Get ready to embark on an exciting journalistic journey through my insightful lens!"
  supriya:
    display_name: Supriya H
    short_name: Supriya
    avatar: supriya.jpg
    email: 210020054@iitdh.ac.in
    instagram: sup_27__
    linkedin: Supriya H
    bio: You can reach out to me anytime, I can be your voice.
  varshitha:
    display_name: Hema Varshitha Bandi
    short_name: Varshitha
    avatar: varshitha.jpg
    email: 210020005@iitdh.ac.in
    instagram: varshitha.bandi
    linkedin: Hema Varshitha Bandi
    bio: Enthusiastic about producing engaging and informative content.
  pushpa:
    display_name: Pushpa Parvathi Battina
    short_name: Pushpa
    avatar: pushpa.jpg
    email: 210010009@iitdh.ac.in
    instagram: pushpa_battina04
    linkedin: parvathi-battina
    bio: Passionate about writing and creating captivating and engaging content for the club.
  upo:
    display_name: Upakramanika
    short_name: Upo
    avatar: upo.png
    email: upakramanika@gmail.com
    instagram: _thequestionmark_
    linkedin: upakramanika-bishnu-339901254
    bio: A self taught digital artist with a keen interest in learning all about design.
  lavanya:
    display_name: Lavanya Shende
    short_name: Lavanya
    avatar: lavanya.jpg
    email: 220120022@iitdh.ac.in
    instagram: lavanya_shende
    linkedin: shende-lavanya-jayant-85a870258
    bio: Immersed in the captivating world of storytelling, I amplify the voices and stories on college campus.
  mukta:
    display_name: Mukta Vedpathak
    short_name: Mukta
    avatar: mukta.jpg
    bio: An amateur and avid writer, here to serve you all the crisp updates and stories around, with a pinch of creativity! 
    twitter: MuktaVedpathak
    instagram: _mukta_vedpathak_29
    linkedin: mukta-vedpathak-1152a8250
    email: muktavedpathak29@gmail.com

# Roles
roles:
  - role: Chief Editors
    members:
      - subham
      - om
      - shahil
  - role: Editors
    members:
      - pushpa
      - varshitha
      - mukta
  - role: Journalists
    members:
      - supriya
      - yash
      - lavanya
  - role: Designers
    members:
      - sid
      - atharva
      - mahesh
      - upo


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
